### ISSUE TITLE
Tried adding rustdoc args to no effect :-/

### ISSUE THREAD

**Issue by carols10cents** [onur/docs.rs#154]
It's entirely possible we're doing something wrong, but I don't know what that something could be.

[We're trying to document private items](https://github.com/rust-lang/crates.io/issues/911) on crates.io's library crate, cargo_registry. We've specified [this in Cargo.toml](https://github.com/rust-lang/crates.io/blob/19e9371fdca24c92b70631787448488155ce1b3f/Cargo.toml#L22-L23):

```toml
[project.metadata.docs.rs]
rustdoc-args = ["--no-defaults --passes collapse-docs --passes unindent-comments"]
```

And then [published version 0.2.0](https://docs.rs/cargo-registry/0.2.0/cargo_registry/), but I don't see private things like [the `DOCUMENTATION_BLACKLIST` constant](https://github.com/rust-lang/crates.io/blob/19e9371fdca24c92b70631787448488155ce1b3f/src/krate.rs#L41-L43) in the docs :(

When I run this command locally, I do see the private items in the generated docs:

```
cargo rustdoc --lib -- --no-defaults --passes collapse-docs --passes unindent-comments
```

Thanks!
